#!/bin/bash
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=64:mem=64gb:ompthreads=4


#============================================================
## ONLY WHEN RUNNING SCRIPT FOR FIRST TIME
echo "Loading miniforge module..."
module load miniforge/3
#============================================================

# Install conda.
eval "$(~/miniforge3/bin/conda shell.bash hook)"
# Disable automatic loading of base environment - to create new environment for each workflow and never modify the base environment (which can break the conda installation).
conda config --set auto_activate_base false
# Add miniforge3 directory (containing conda, etc.) to job PATH.
PBS_O_PATH=$PBS_O_PATH:/rds/general/user/nb122/home/miniforge3/
# Activate conda environment.
echo "Activating conda environment..."
conda activate blastn_raxmlconda

cd $PBS_O_WORKDIR

echo " "
echo " "


#---------------------------------------------------------------------------------------------------

# Run RAxML.
echo "Running RAxML..."
raxml-ng --all --msa T2.raxml.rba --data-type BIN --model GTR+I+G4 --bs-trees 1000  --prefix blastn_raxmlng --threads 4

echo " "
echo " "

#---------------------------------------------------------------------------------------------------


# Deactivate conda environment.
echo "Deactivating conda environment..."
conda deactivate

# Print job's environment.
echo "Printing job environment..."
printenv
