#!/bin/bash
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=12:mem=36gb:ompthreads=4
#PBS -e ./blastn_check_errors -o ./blastn_check_output

module load intel-suite/2019.4
module load blast+/2.11.1

cd $PBS_O_WORKDIR


# Copy the input file into the temporary directory used during the job.
cp ../../../Lplantarum-nuc-seq-file.txt $TMPDIR

# Run the BLAST+ application's command.
echo "blastn -task blastn -db core_nt -query ../../../Lplantarum-nuc-seq-file.txt -remote -out blastn_check_result.txt -outfmt "6 sacc slen stitle staxid pident evalue sstart send sseq" -evalue 1e-5 -word_size 11 -perc_identity 60 -max_target_seqs 100000 -dust no -soft_masking false"
blastn -task blastn -db core_nt -query ../../../Lplantarum-nuc-seq-file.txt -remote -out blastn_check_result.txt -outfmt "6 sacc slen stitle staxid pident evalue sstart send sseq" -evalue 1e-5 -word_size 11 -perc_identity 60 -max_target_seqs 100000 -dust no -soft_masking false

# Print the job's environment.
printenv

