
#!/bin/bash
#PBS -l walltime=00:15:00
#PBS -l select=1:ncpus=4:mem=8gb:ompthreads=4
#PBS -e ./outfmt4_errors -o ./outfmt4_output

module load intel-suite/2019.4 
module load blast+/2.11.1
cd $PBS_O_WORKDIR


# Copy the input file into the temporary directory used during the job.
cp $PBS_O_WORKDIR/Lplantarum-prot-seq-file.txt $TMPDIR

# Run the BLAST+ application's command.
blastp -db refseq_select_prot -query Lplantarum-prot-seq-file.txt -remote -out outfmt4_result.txt -outfmt 4 -evalue 1e-7 -matrix BLOSUM62 -word_size 5 -entrez_query "Archaea[organism]" -max_target_seqs 5000


# Print the job's environment.
echo "Details of the job..."
printenv
