#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=64:mem=180gb:ompthreads=16


#============================================================
## ONLY WHEN RUNNING SCRIPT FOR FIRST TIME
echo "Loading miniforge module..."
module load miniforge/3
#============================================================

# Install conda.
eval "$(~/miniforge3/bin/conda shell.bash hook)"
# Disable automatic loading of base environment - to create new environment for each workflow and never modify the base environment (which can break the conda installation).
conda config --set auto_activate_base false
# Add miniforge3 directory (containing conda, etc.) to job PATH.
PBS_O_PATH=$PBS_O_PATH:/rds/general/user/nb122/home/miniforge3/
# Activate conda environment.
echo "Activating conda environment..."
conda activate blastp_raxmlconda

cd $PBS_O_WORKDIR

echo " "
echo " "


#---------------------------------------------------------------------------------------------------

# Run RAxML.
echo "Running RAxML..."
raxml-ng --all --msa parameters.raxml.rba --data-type BIN --model LG+I+G4+F --bs-trees 1000  --prefix blastp_secondtime  --threads 16

#---------------------------------------------------------------------------------------------------


# Deactivate conda environment.
echo "Deactivating conda environment..."
conda deactivate

# Print job's environment.
echo "Printing job environment..."
printenv
