
#!/bin/bash
#PBS -l walltime=00:50:00
#PBS -l select=1:ncpus=8:mem=20gb:ompthreads=4
#PBS -e ./blastn_outfmt6_errors -o ./blastn_outfmt6_output

module load intel-suite/2019.4 
module load blast+/2.11.1

cd $PBS_O_WORKDIR


# Copy the input file into the temporary directory used during the job.
cp $PBS_O_WORKDIR/Lplantarum-nuc-seq-file.txt $TMPDIR

# Run the BLAST+ application's command. (maxtargetseqs 4000)
blastn -db core_nt -query Lplantarum-nuc-seq-file.txt -remote -out blastn_outfmt6_result.txt -outfmt "6 sacc slen stitle pident evalue qstart qend sstart send sseq length mismatch" -evalue 1e-5 -word_size 11 -perc_identity 60 -max_target_seqs 10


# Print the job's environment.
printenv

