#!/bin/bash
#PBS -l walltime=00:50:00
#PBS -l select=1:ncpus=8:mem=16gb:ompthreads=4

echo "Loading Clustal Omega HPC module..."
module load clustalo/1.2.4

echo " "

cd $PBS_O_WORKDIR

# Copy input file into job's temporary directory.
echo "Copying input file/s into TMPDIR..."
cp ../../blastp_representative50.fasta $TMPDIR

echo " "
echo " "


#---------------------------------------------------------------------


# Run the Clustal Omega alignment.
echo "Running Clustal Omega..."
clustalo --in=$PBS_O_HOME/Y3_Project/BLASTP/Refseq_select_prot_e7/blastp_representative50.fasta --infmt=fa --out=blastp_rep_aligned50.fasta --outfmt=fa -t Protein

echo " "
echo " "


#---------------------------------------------------------------------


# Print the job's environment.
echo "Printing job environment..."
printenv
