#!/bin/bash
#PBS -l walltime=00:45:00
#PBS -l select=1:ncpus=8:mem=24gb


cd $PBS_O_WORKDIR

# Copy input files and cd-hit master folder into job's temporary directory.
echo "Copying input files into TMPDIR..."
#cp blastn_clustered.clstr $TMPDIR
cp blastn_dataset $TMPDIR
cp blastn_newfasta.fasta $TMPDIR
cp -r cd-hit-v4.8.1-2019-0228 $TMPDIR

echo " "

# Inspecting $TMPDIR and $PBS_O_WORKDIR to confirm all expected files are present.
echo "Investigating TMPDIR..."
echo $TMPDIR
ls $TMPDIR

echo " "

echo "Investigating PBS_O_WORKDIR..."
echo $PBS_O_WORKDIR
ls $PBS_O_WORKDIR

echo " "
echo " "


#-----------------------------------------------------------------------------


# Load blast+/2.11.1 module (and its intel-suite dependency) from HPC.
echo "Loading required HPC modules..."
module load intel-suite/2019.4
module load blast+/2.11.1
# (BLAST+ is required for a certain argument of psi-cd-hit.pl command.)

echo " "
echo " "


# Install and compile cd-hit package.
#echo "Install and compile cd-hit package"
#cd cd-hit-v4.8.1-2019-0228
#make
echo "cd-hit package already installed and compiled from prior runs."
echo " "

#echo "Install and compile cd-hit-auxtools"
#cd cd-hit-auxtools
#make
echo "cd-hit-auxtools already installed and compiled from prior runs."

echo " "
echo " "


#-----------------------------------------------------------------------------


# Investigating whether cd-hit directory is found in $TMPDIR --> YES.
echo "Checking whether 'cd-hit' is found in TMPDIR..."
find $TMPDIR -name "cd-hit*"

# Add cd-hit directory to PATH.
PBS_O_PATH=$PBS_O_PATH:/var/tmp/pbs.$PBS_JOBID/cd-hit-v4.8.1-2019-0228/

echo " "

# Investigating whether cd-hit-est is found in $TMPDIR --> YES.
echo "Checking whether 'cd-hit-est' is found in $TMPDIR..."
find $TMPDIR -name "cd-hit-est"

echo " "

# Investigating whether make_multi_seq.pl is found in $TMPDIR --> YES.
echo "Checking whether 'make_multi_seq.pl' is found in TMPDIR..."
find $TMPDIR -name "make_multi_seq.pl"

echo " "
echo " "


# Run CD-HIT-EST to cluster nucleotide sequences.
echo "Running CD-HIT-EST to cluster BLASTN nucleotide sequences..."
/var/tmp/pbs.$PBS_JOBID/cd-hit-v4.8.1-2019-0228/cd-hit-est -i blastn_dataset -o blastn_clustered -c 0.95 -G 1 -M 0 -d 0 -n 9

echo " "

# Run make_multi_seq.pl to generate separate FASTA file for each cluster.
# 'Cluster_FASTAs' indicates the directory the output files will be saved in.
# '1' included at end so that separate FASTA files are created for clusters containing more than one sequence (i.e., all of them).
#echo "Running make_multi_seq.pl..."
#/var/tmp/pbs.$PBS_JOBID/cd-hit-v4.8.1-2019-0228/make_multi_seq.pl blastn_dataset blastn_clustered.clstr Cluster_FASTAs 1

#echo " "

# Run PSI-CD-HIT command to cluster *long* nucleotide sequences.
#/var/tmp/pbs.$PBS_JOBID/cd-hit-v4.8.1-2019-0228/psi-cd-hit/psi-cd-hit.pl -i blastn_dataset -o blastn_clustered -c 0.95 -g 1 -M 0
#./psi-cd-hit.pl -i blastn_fasta.fasta -o blastn_clustered.fasta -c 0.95 -prog blastn -exec qsub -core 8 

echo " "
echo " "


#-----------------------------------------------------------------------------


# Print job environment.
echo "Printing job environment..."
printenv

