#!/bin/bash
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=16:mem=32gb:ompthreads=4


cd $PBS_O_WORKDIR

# Copy input files into job's temporary directory.
echo "Copying input files into TMPDIR..."
cp ../../../blastn_representative.fasta $TMPDIR
#cp -r kalign-3.4.0.tar.gz $TMPDIR -> CAN DELETE THIS ONCE UNZIPPED.

echo " "

echo "Investigating TMPDIR..."
echo $TMPDIR
ls $TMPDIR

echo " "
echo " "

echo "Investigating PBS_O_WORKDIR..."
echo $PBS_O_WORKDIR
ls $PBS_O_WORKDIR

echo " "
echo " "


#---------------------------------------------------------------------------------------------------


# Compile kalign.
#echo "Unzipping and compiling kalign..."
#tar -zxvf kalign-3.4.0.tar.gz
#echo " "

#cd kalign-3.4.0

echo "'build' directory already made from prior runs."
#echo "Creating 'build' directory inside 'kalign-3.4.0'..."
##mkdir build
echo " "

#cd build

echo "Kalign already compiled from prior runs."
#echo "Compiling kalign..."
#cmake ..
#make
echo " "

echo "'test' already performed and successful from prior runs."
#echo "Making and performing 'test'..."
#make test
echo " "

echo "'install' already performed and successful from prior runs."
#echo "Making and performing 'install'..."
#make install

echo " "
echo " "


# Add kalign directory to PATH.
echo "Adding kalign directory to PATH..."
PBS_O_PATH=$PBS_O_PATH:/rds/general/user/nb122/home/Y3_Project/BLASTN/kalign-3.4.0/
echo " "

cp -r /rds/general/user/nb122/home/Y3_Project/BLASTN/kalign-3.4.0/ $TMPDIR
# Check if kalign directory in TMPDIR. --> YES.
echo "Checking if kalign successfully copied into and found in TMPDIR..."
find $TMPDIR -name "kalign"


#---------------------------------------------------------------------------------------------------


echo " "
echo " "

#cd $PBS_O_WORKDIR

# Run kalign to align DNA sequences.
echo "Running kalign..."
/var/tmp/pbs.$PBS_JOBID/kalign-3.4.0/build/src/kalign -i /var/tmp/pbs.$PBS_JOBID/blastn_representative.fasta -f fasta -o blastn_aligned.fasta --type dna


#---------------------------------------------------------------------------------------------------


echo " "
echo " "

# Print job's environment.
echo "Printing job environment..."
printenv

